version: '3.8'

services:
  soccer-predictor:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DEBUG=False
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Database service for production
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: soccer_data
      POSTGRES_USER: soccer_user
      POSTGRES_PASSWORD: soccer_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    profiles:
      - production

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    profiles:
      - production

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: soccer-predictor-network